### ISSUE TITLE
open source

### ISSUE THREAD

**Issue by dweinstein** [nowsecure/node-applesign#1]
* [x] MIT license
* [x] Move repository to `nowsecure` and drop the /private/ bit
* [x] lint semistandard warnings https://github.com/viaforensics/node-applesign/issues/4
* [x] publish to npm

**Comment by radare** [comment]
I think we should rename the `ipa-resign.js` to something more related to the modulename like `applesign-ipa`

**Comment by trufae** [comment]
Everything is done now :) just pending to rename that ipa-resign.js if everybody agrees
