### ISSUE TITLE
doesn't generate ipa at end

### ISSUE THREAD

**Issue by dweinstein** [nowsecure/node-applesign#12]
it's broke ;-)

**Comment by trufae** [comment]
Should be fixed now, please confirm

**Comment by dweinstein** [comment]
nope not working yet

**Comment by dweinstein** [comment]
it's working for me now

**Comment by trufae** [comment]
Fixed in https://github.com/nowsecure/node-applesign/commit/40dd00c04b34142de60a18f288a47d0936998da7

thanks for reporting
