### ISSUE TITLE
Can't sign app directory

### ISSUE THREAD

**Issue by lord** [nowsecure/node-applesign#135]
When signing an app directory, I get a "Incorrect arguments count" error. It looks like signAppDirectory [expects two arguments](https://github.com/nowsecure/node-applesign/blob/9648a9fbbf75d615816a505d4683ef3a04ac1318/index.js#L137), but the applesign binary will only call it with [one argument](https://github.com/nowsecure/node-applesign/blob/master/bin/applesign.js#L50)?

**Comment by trufae** [comment]
Thanks for reporting that! i fixed that and tagged a new release `3.9.2` . Happy new year!

**Comment by lord** [comment]
Thanks for the quick fix — just tested it and it seems to work great. Happy new year to you too!
