### ISSUE TITLE
Unable to resign apps with WatchKit

### ISSUE THREAD

**Issue by oleavr** [nowsecure/node-applesign#34]
Due to `a sealed resource is missing or invalid`, which leads to an error when trying to install the app: `AppexBundleIDNotPrefixed`.

**Comment by trufae** [comment]
Can you confirm if this is fixed now?

**Comment by trufae** [comment]
There's also the -w flag which removes the watchapp stuff from the IPA and allows to sign and deploy properly. I think we can close this issue

**Comment by trufae** [comment]
ping

**Comment by oleavr** [comment]
Haven't encountered this since then, and can't remember which app it was. Let's consider this fixed.
