### ISSUE TITLE
Add step to lipo all fat binaries

### ISSUE THREAD

**Issue by trufae** [nowsecure/node-applesign#36]
this will allow to reduce final IPA size and also, avoid having cracked IPAs that contain archs not supported.

The tool must enumerate all the archs for all the fat bins in the ipa and identify the minimum common supported to strip the rest.

**Comment by dweinstein** [comment]
👍

**Comment by trufae** [comment]
Fixed in https://github.com/nowsecure/node-applesign/commit/b8236e3ad1e4811ffd9ab01835a8dd78552924d6
