### ISSUE TITLE
Discard or sign orphaned frameworks

### ISSUE THREAD

**Issue by trufae** [nowsecure/node-applesign#52]
If the ipa contains orphaned mach0 binaries (not referenced from any other mach0) it will fail on install, but will run fine, the problem is that applesign will just not sign them because they are out of the dependency tree and this will make installd unhappy

**Comment by dweinstein** [comment]
Could we also leave them but sign them anyway?

**Comment by trufae** [comment]
The last release is just adding them to the signing queue, the other option would be to remove them from the IPA, but that can result in undesired behaviour if the app is dlopening them at runtime, so I think this default is fine for now. We can investigate later if parametrizing this action makes sense or not
