### ISSUE TITLE
validation

### ISSUE THREAD

**Issue by 0x5e** [nowsecure/node-applesign#56]
Hello, when I'm re-signing apps, I always meet problems.`codesign -vv xxx.app` doesn't validate all things iOS system do.
For example: bundle_id/entitlements/certificate not match mobileprovision file; certificate expired; certificate revoked; .framework/.dylib/.appex not re-signed properly;
These problems was found after I failed to install .ipa on the device then check and check again.
What do you think,  if validations can be done before re-sign operation?

**Comment by trufae** [comment]
You can use the -c to clone the entitlements from your mobileprovisioning and solve this inconsistency problem. Not all checks can be done without a device.
