### ISSUE TITLE
consider specifying min node version in package.json

### ISSUE THREAD

**Issue by dweinstein** [nowsecure/node-applesign#70]
https://docs.npmjs.com/files/package.json#engines

related to https://github.com/nowsecure/node-applesign/pull/68

**Comment by raulsiles** [comment]
The error that originated PR #68 was:
```
$ ./applesign.js -h
/Users/siles/ROOT/Applications/node-applesign/session.js:440
        groups.push(...newGroups);
                    ^^^

SyntaxError: Unexpected token ...
```

It was generated when using the following old NodeJS versions:
```
$ node -v
v4.1.1
$ npm -v
2.14.4
```

After updating to newer versions (supporting the ES6 syntax), the error was fixed:
```
$ node -v
v8.9.3
$ npm -v
5.5.1
```

**Comment by trufae** [comment]
According to http://node.green/ the spread operator was introduced in NodeJS 5.12
