### ISSUE TITLE
How to insert .dylib to an IPA file?

### ISSUE THREAD

**Issue by pharazone** [nowsecure/node-applesign#72]
I used
bin/applesign.js -I FridaGadget.dylib

but it seems something wrong:
Error: not found: insert_dylib

**Comment by rustymagnet3000** [comment]
Why not use Objection to do the whole thing for you?

https://github.com/sensepost/objection

It uses AppleSign under the hood and repackages the ipa with Frida-Gadget.  You need ios-deploy to provision the app bundle.

**Comment by trufae** [comment]
You have to install the `insert_dylib` tool in your system. For example via r2pm:

`r2pm -i insert_dylib`
