### ISSUE TITLE
resigning app w/ space in executable

### ISSUE THREAD

**Issue by dweinstein** [nowsecure/node-applesign#8]
```
[ERROR] ./PersonalFoo.ipa.d/Payload/Personal Foo.app/Personal Foo: resource envelope is obsolete (custom omit rules)

```

cc @trufae

**Comment by trufae** [comment]
The error is not related to having spaces, but the app being signed by an old xcode (according to google), the error that is happening is this: http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process i have no commit access, so i'm submiting a pullreq for it
