### ISSUE TITLE
Trouble Signing Apps due to `mkdir`

### ISSUE THREAD

**Issue by leonjza** [nowsecure/node-applesign#89]
As the title says, [this issue comment](https://github.com/sensepost/objection/issues/286#issuecomment-544951353) shows a case where `applesign` appears to fail creating directories while doing its thing, with a weird workaround.

**Comment by C3l1n** [comment]
I fixed it in my fork. Best regards.

**Comment by trufae** [comment]
Can you submit a pr?

**Comment by C3l1n** [comment]
Done.
