### ISSUE TITLE
Can't override the get-task-allow to false

### ISSUE THREAD

**Issue by jsramraj** [nowsecure/node-applesign#91]
When resigning my .iPa with new distribution certificate, I try override the entitlement `get-task-allow` to false by using the following code. But the value never changes in the signed ipa file.

`const as = new Applesign({
                    withGetTaskAllow: false,
                    identity: 'path to certificate',
                    mobileprovision: 'path to mobileprovision',
                });`

**Comment by jsramraj** [comment]
I looked at the code and I found that the block never executes if the `withGetTaskAllow` is set to `false`.

```
if (this.config.withGetTaskAllow) {
      if (entMacho['get-task-allow'] !== true) {
        this.emit('message', 'get-task-allow set to true');
        entMacho['get-task-allow'] = true;
        changed = true;
      }
    }
```

**Comment by trufae** [comment]
this is fixed in master in https://github.com/nowsecure/node-applesign/pull/92
