### ISSUE TITLE
Node apple sign not displaying all commands advertised.

### ISSUE THREAD

**Issue by professorIsaac** [nowsecure/node-applesign#99]

**Comment by trufae** [comment]
What do you mean?

**Comment by professorIsaac** [comment]
Usage:

  applesign [--options ...] [target.ipa | Payload/Target.app]

  -a, --all                     Resign all binaries, even it unrelated to the app
  -b, --bundleid [BUNDLEID]     Change the bundleid when repackaging
  -c, --clone-entitlements      Clone the entitlements from the provisioning to the bin
  -f, --force-family            Force UIDeviceFamily in Info.plist to be iPhone
  -h, --help                    Show verbose help message
  -H, --allow-http              Add NSAppTransportSecurity.NSAllowsArbitraryLoads in plist
  -i, --identity [1C4D1A..]     Specify hash-id of the identity to use
  -L, --identities              List local codesign identities
  -m, --mobileprovision [FILE]  Specify the mobileprovision file to use
  -o, --output [APP.IPA]        Path to the output IPA filename
  -O, --osversion 9.0           Force specific OSVersion if any in Info.plist
  -w, --without-watchapp        Remove the WatchApp from the IPA before resigning
  -W, --without-xctests         Remove the XCTests from the resigned IPA

Example:

  $ applesign -w -c -m embedded.mobileprovision target.ipa

**Comment by professorIsaac** [comment]
These are less than advertised in readme.

**Comment by professorIsaac** [comment]
@trufae I installed it globally what do I do I need some of the missing options.

**Comment by trufae** [comment]
if you dont provide any argument to applesign it will display a short help message with just the most common/used options. Use -h or --help to get the full help message
